pipeline:
    backend:
        image: python:3
        group: build
        commands:
            - cd backend
            - . env/bin/activate
            - python src/manage.py migrate
    frontend:
        image: python:3
        group: build
        commands:
            - echo "Simulating frontend build ..."
    deploy_backend:
        image: appleboy/drone-ssh
        group: deploy
        when:
            branch: master
            event: push
        host: ace.ulv.io
        port: 22
        username: root
        secrets: [ ssh_key ]
        script:
            - "Simulating backend deploy ..."
            - date
    deploy_frontend:
        image: appleboy/drone-ssh
        group: deploy
        when:
            branch: master
            event: push
        host: ace.ulv.io
        port: 22
        username: root
        secrets: [ ssh_key ]
        script:
            - "Simulating frontend deploy ..."
            - date
