pipeline:
  # Restore potentially cached build folders
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - backend/env
      - frontend/node_modules
    volumes:
      - /tmp/drone-cache:/cache

  # Install dependencies and test the python code
  backend:
    image: python:3
    group: build
    commands:
      - cd backend
      - make env
      - . env/bin/activate
      - make install
      - make test
  # Install dependencies, build and test the typescript code
  frontend:
    image: node:10-alpine
    group: build
    commands:
      - cd frontend
      - yarn install
      - yarn run build:prod
      - yarn run test

  # Deploy backend to prod
  deploy_backend:
    image: appleboy/drone-ssh
    group: deploy
    when:
      branch: master
      event: push
    host: ace.ulv.io
    port: 22
    username: root
    secrets: [ ssh_key ]
    script:
      - echo "Simulating backend deploy ..."
      - date

  # Deploy frontend to prod
  deploy_frontend:
    image: appleboy/drone-ssh
    group: deploy
    when:
      branch: master
      event: push
    host: ace.ulv.io
    port: 22
    username: root
    secrets: [ ssh_key ]
    script:
      - echo "Simulating frontend deploy ..."
      - date

  # Rebuild cache volume from current build workspace
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./backend/env
      - ./frontend/node_modules
    volumes:
      - /tmp/drone-cache:/cache
