version: '3.6'

services:
  # Django container
  backend:
    build: backend/
    image: mythern/overflow-backend
    restart: unless-stopped
    env_file: backend/src/.env
    volumes:
      - staticfiles:/app/static
    depends_on:
      - db
      - redis

  # nginx container
  frontend:
    build: frontend/
    image: mythern/overflow-frontend
    restart: unless-stopped
    ports:
      - "9001:80"
    networks:
      - default
      - traefik
    volumes:
      - staticfiles:/usr/share/nginx/html/static:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.rule=Host:overflow.no"
      - "traefik.protocol=https"
      - "traefik.port=80"
    depends_on:
      - backend

  # PostgreSQL container
  db:
    image: postgres:10-alpine
    restart: unless-stopped
    env_file: backend/src/.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  # Cache container
  redis:
    image: redis:alpine
    restart: unless-stopped

# Define the Traefik network for auto detection from forward proxy
networks:
  traefik:
    external: true

# Define shared data volumes
volumes:
  staticfiles:
